If PR labels are missing, check again
ausaccessfed/workflows pull request #264
Opened 2024-07-28 23:55 UTC by matthew-puku

Renovate PRs occasionally fail to automerge. We think this is because labels aren't always present the instant this workflow runs. To work around this, we now try fetching labels for Renovate PRs for up to 50 seconds.

We stop after 50 seconds so we don't cross GitHub's minute billing boundary.

2024-07-29 05:17 UTC, phyzical commented on .github/workflows/pr-housekeeping.yml
> +                    currentWaitTime *= 2 // Back-off exponentially
hmm is this needed? this will result in like under 5 seconds of checking no?

as itll be 
totalWaitTime = 1000
3000
11000
27000
ect

2024-07-29 05:18 UTC, phyzical commented on .github/workflows/pr-housekeeping.yml
> +                    currentWaitTime *= 2 // Back-off exponentially
Oh nvm. it still waits that time 😆

2024-07-29 05:18 UTC, phyzical approved these changes

2024-07-29 05:19 UTC, phyzical requested changes
Oh actaully..

Your example is old (it was created in jan)

The referenced pr is actually from before the changes that fixed the issue.

If you can find a more recent example though happy to merge.

2024-07-29 06:17 UTC, matthew-puku commented
Here's one from July 17: https://github.com/ausaccessfed/discovery-service/pull/673

2024-08-08 01:01 UTC, phyzical approved these changes

2024-08-08 01:02 UTC, phyzical commented
hmm fair enough dont see any reason why that one wouldnt work

2024-08-13 21:55 UTC, merged