POC for distributing common workflows
ausaccessfed/workflows pull request #64
Opened 2023-11-24 05:20 UTC by phyzical

2023-11-26 22:37 UTC, matthew-puku requested changes
Looks pretty good — probably worth pursuing further?

To productionize, I'd say must-haves are:

- eslint
- prettier
- a comment at the top of the distributed workflow files linking to the source file at the current version (e.g. https://github.com/ausaccessfed/workflows/blob/6953eade8b4a9b5ba1ed4e2a4210b40cf1a11a76/.github/renovate-config.js)
- various nits

As well as that, it'd be nice if there were some way to un-distribute the workflows as well. I'm pretty sour on things which allow easy create/update but make it a PITA to delete.

2023-11-27 00:48 UTC, phyzical commented
>     * eslint
>     * prettier

I dont think we should automate this, as you may have projects that already have node_modules, leading to complicated replacements, also leads into the realm of app specific ness. i had a thought about just bootstrapping configs but i dont think thats worth the effort either. as once its done its done, it wont change much from a distribution point of view.

HMM actually how about a set of "only bootstrapping if missing" files? or rather "once-off-distributions`

>     * a comment at the top of the distributed workflow files linking to the source file at the current version (e.g. https://github.com/ausaccessfed/workflows/blob/6953eade8b4a9b5ba1ed4e2a4210b40cf1a11a76/.github/renovate-config.js)

This should be possible 👍 

> As well as that, it'd be nice if there were some way to un-distribute the workflows as well. I'm pretty sour on things which allow easy create/update but make it a PITA to delete.

This one is "possible" But how would we know to remove a workflow? for example, a merge goes into main that renames or removes a workflow. the distribution runs and loops the files. itll no longer be there.

I guess it would end up being get a list of files from latest commit and get a list of files form the previous main commit are there differences?

2023-11-28 03:15 UTC, phyzical commented
This should be ready for review again

2023-11-28 03:21 UTC, phyzical commented on scripts/workflow-distributor.js
> +    repositories = ['ausaccessfed/reporting-service']
```suggestion
```

To be removed at end

2023-11-28 03:22 UTC, phyzical commented on .github/workflows/workflow-distributor.yml
> +    # - main
```suggestion
     branches:
       - main
```

to be reenabled at the end

2023-11-28 03:27 UTC, matthew-puku commented on scripts/workflow-distributor.js
> +            message: "Updating Distributable Files",
```suggestion
            message: "Update distributable files",
```

2023-11-28 03:27 UTC, matthew-puku commented on scripts/workflow-distributor.js
> +const CONSTANTS = {
Is it possible to prettier/lint this file? It's big

2023-11-28 03:27 UTC, matthew-puku commented on README.md
> +* If it contains `#ONCE#`, the file will only ever be added once, if its already found then nothing is done
Great approach 👍

2023-11-28 03:28 UTC, matthew-puku approved these changes

2023-11-28 03:28 UTC, phyzical commented on scripts/workflow-distributor.js
> +const CONSTANTS = {
it already is linted, is there some rule were expecting thats not enforced?

2023-11-28 03:28 UTC, matthew-puku commented on README.md
> +This repo contains the source for the reusable workflows used by many of the apps throughout aaf
```suggestion
This repo contains the reusable workflows used by many of the app repos throughout AAF.
```

2023-11-28 03:29 UTC, matthew-puku commented on scripts/workflow-distributor.js
> +        }
Handle workflow dispatch?

2023-11-28 03:31 UTC, matthew-puku commented on scripts/workflow-distributor.js
> +const CONSTANTS = {
I thought we generally used 2 spaces to indent, not 4, so I assumed it wasn't formatted. 🤷

2023-11-28 03:32 UTC, matthew-puku commented on scripts/workflow-distributor.js
> +        }
Or I guess just remove workflow dispatch, if it's not necessary (perhaps push to master is enough)

2023-11-28 03:33 UTC, phyzical commented on scripts/workflow-distributor.js
> +        }
good point, was just gonna handle that second, but looking at the payload docs it should be sender`https://docs.github.com/en/webhooks/webhook-events-and-payloads#workflow_dispatch`

2023-11-28 03:36 UTC, phyzical commented on scripts/workflow-distributor.js
> +const CONSTANTS = {
it might be what eslint psuhes on us via 

`"extends": ["airbnb-base", "plugin:prettier/recommended", "plugin:yml/standard"],`

2023-11-28 03:37 UTC, matthew-puku commented on scripts/workflow-distributor.js
> +                message: `Updating ${fileNameRaw}`,
```suggestion
                message: `Update ${fileNameRaw}`,
```

2023-11-28 03:38 UTC, waldofouche commented on README.md
> +* If it contains `#PARTIAL#`, the file assumes that from top fo the file down to the last line will be replaced in the source repo if it exists, otherwise it is just added verbatim
```suggestion
* If it contains `#PARTIAL#`, the file assumes that from the top of the file down to the last line will be replaced in the source repo if it exists, otherwise it is just added verbatim
```

2023-11-28 03:40 UTC, waldofouche approved these changes

2023-11-28 03:40 UTC, waldofouche commented on .github/workflows/distributions/.dockleignore
> +#ONCE#
Any global ignores worth adding in now?

2023-11-28 03:41 UTC, waldofouche commented on .github/workflows/distributions/.eslintrc
> +#ONCE#
Not related to this file, but are you planning on adding a global `.streerc` as well?

2023-11-28 03:42 UTC, waldofouche commented on .github/workflows/distributions/.eslintrc
> +#ONCE#
al lol, was lower down, ignore

2023-11-28 03:43 UTC, phyzical commented on .github/workflows/distributions/.dockleignore
> +#ONCE#
nah its more of a justincase its needed thing

2023-11-28 04:19 UTC, phyzical commented on scripts/workflow-distributor.js
> +  repositories = ['ausaccessfed/reporting-service']
```suggestion
```

2023-11-28 04:33 UTC, merged